name: Compile Sketch

# The workflow will run on every push and pull request to the repository
on:
  - push
  - pull_request

jobs:
  compile-sketch:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        fbqn:
          - arduino:avr
          - arduino:samd:nano_33_iot
          
        
    


    steps:
      # This step makes the contents of the repository available to the workflow
      - name: Checkout repository
        uses: actions/checkout@v2

      # For more information: https://github.com/arduino/compile-sketches#readme
      - name: Compile sketch
        uses: arduino/compile-sketches@v1.0.1
        with:
          sketch-paths: |
            # Configure the action to search all folders under the root of the repository for sketches and compile them.
            # This is formatted as a YAML list, which makes it possible to have multiple sketch paths if needed.
            - ./examples/
          libraries: |
            - source-path: ./
